# Application Configuration
app:
  name: "Template App"
  version: "1.0.0"

# Server Configuration
server:
  port: 8080
  gin_mode: "debug"  # Mode: "debug", "release"
  log_level: "info"  # Logging level: "debug", "info", "warn", "error"

# Database Configuration (PostgreSQL)
database:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "postgres"
  dbname: "postgres"
  sslmode: "disable"

storage:
  host: "localhost"
  port: 9010
  bucket_name: "my-bucket"
  access_key: "minioadmin"
  secret_key: "minioadmin"
  region: "us-west2"

mail:
  host: "smtp.mailtrap.io"
  port: 587
  username: "b7173fa8081cc5"
  password: "061765b29425a0"
  from: "no-reply@yourapp.com"
  insecure_skip_verify: true
