# Application Configuration
app:
  name: "Template App"
  version: "1.0.0"

# Server Configuration
server:
  port: 8080
  gin_mode: "debug"  # Mode: "debug", "release"
  log_level: "info"  # Logging level: "debug", "info", "warn", "error"

storage:
  host: "bucket.railway.internal"
  port: 9000
  bucket_name: "my-bucket"
  access_key: "CmpfqWiu0jMcN7dUsoFr"
  secret_key: "HJ3beh6d60L7ktIJjLKScARtOLwJuMfvREkAKu3U"
  region: "us-west2"
