name: Go CI

on:
  push:
    branches:
      - main # จะ deploy เมื่อ push เข้า main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'

      - name: Install dependencies
        run: go mod tidy

      - name: Build binary
        run: go build -o app ./cmd/server

      - name: Deploy to Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          railway up --service template-system-go --detach
